### ISSUE TITLE
error TS2305:: rxjs/Rx"' has no exported member 'ObservableInput'.

### ISSUE THREAD

**Issue by ernitinjain** [tjoskar/ng-lazyload-image#366]
When I am using the latest version 5.0.0 with Angular I am getting below error, It works perfectly with v4.0.0

> ERROR in node_modules/ng-lazyload-image/src/types.d.ts(1,22): error TS2305: Module '"/Users/apple/NJ/projects-2018/KFC-UKI/kfc-webapp-loyalty_delivery/node_modules/rxjs/Rx"' has no exported member 'ObservableInput'.

**Comment by tjoskar** [comment]
Humm... What version of rxjs and Angular are you using?

**Comment by zarinara** [comment]
> Angular: 5.2.11
> rxjs: 5.5.12

you must use rxjs 6 and angular 7

**Comment by tjoskar** [comment]
@ernitinjain, `ng-lazyload-image` is requiring rxjs@6 and angular@6. You should receive a warning while installing `ng-lazyload-image` (https://github.com/tjoskar/ng-lazyload-image/blob/master/package.json#L34-L37)

You have to downgrade `ng-lazyload-image` to `3.4.2` if you want to use it with rxjs@5 and angular@5.

**Comment by nashwan-nasser** [comment]
thnx tjoskar

**Comment by Anujmoglix** [comment]
When i am downgrading then i am getting https://github.com/tjoskar/ng-lazyload-image/issues/366 this issue and  not able to use LazyLoadImageModule.forRoot({
  preset: intersectionObserverPreset
}) . what to do ?

**Comment by tjoskar** [comment]
@Anujmoglix, Can you please create a new issue where you specify the version of `ng-lazyload-image`, `angular` and `rxjs` that you are using? You can get the version by: `npm ls ng-lazyload-image`, `npm ls @angular/core` and `npm ls rxjs`.

**Comment by Rupeshiya** [comment]
@tjoskar Now is this, usable with angular v5 ?

**Comment by tjoskar** [comment]
@Rupeshiya, the angular team it self does not support [Angular v5](https://angular.io/guide/releases) and I do only support version 7 and 8. And soon I will probably only support version 8.

**Comment by Meyank** [comment]
Hey i am using angular, rsjx, fire2 version 6.14.6...and getting this issue. can someone help me which version i should move to??

**Comment by tjoskar** [comment]
Hi @Meyank, 

Can you open a new issue (with a link to this one) where you state your version of rxjs, angular and `ng-lazyload-image`? And if possible a link to a project where you can reproduce the error.
